version: 0.2

env:
  variables:
    s3_output: "staff-intranet-leblibrary"
    hugo_version: "0.55.6"

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
      - dpkg -i hugo_${hugo_version}_Linux-64bit.deb
    finally:
      - hugo version
  pre_build:
    commands:
      - git submodule init
      - git submodule update --remote
  build:
    commands:
      - cd intranet
      - hugo
      - cd public && aws s3 sync . s3://${s3_output} --delete --acl public-read
      - aws cloudfront create-invalidation --distribution-id ${CLOUDDIST} --paths "/*"
    finally:
      - echo "Script finished running"
